# Generated by Django 3.1.7 on 2021-03-26 08:55

import BikeRentalApi.enums
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('state', django_enumfield.db.fields.EnumField(default=0, enum=BikeRentalApi.enums.StationState)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BikeRentalApi.person')),
            ],
            bases=('BikeRentalApi.person',),
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BikeRentalApi.person')),
            ],
            bases=('BikeRentalApi.person',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='BikeRentalApi.person')),
            ],
            bases=('BikeRentalApi.person',),
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_state', django_enumfield.db.fields.EnumField(default=0, enum=BikeRentalApi.enums.BikeState)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApi.bikestation')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApi.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApi.user')),
            ],
        ),
    ]
