# Generated by Django 3.1.7 on 2021-03-31 08:32

import BikeRentalApi.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=django_enumfield.db.fields.EnumField(default=0, enum=BikeRentalApi.enums.UserState),
        ),
    ]
