# Generated by Django 3.2 on 2021-04-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApi', '0003_alter_rental_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='end_date',
        ),
    ]
