# Generated by Django 3.1.7 on 2021-04-11 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApi', '0003_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BikeRentalApi.bikestation'),
        ),
    ]
