# Generated by Django 3.1.7 on 2021-05-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeRentalApi', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikestation',
            name='bikes_limit',
            field=models.IntegerField(default=10),
        ),
    ]
